### PR TITLE
Initial build of website.

### PR DESCRIPTION
**Pull request by MJJBennett**
@MykalMachon I'm looking into a strategy to build and then clean the website right after, so the local development branch doesn't look quite this messy. However, this should probably work for now.

### CODE REVIEW

**Comment by MykalMachon** [comment]
@MJJBennett as a temporary solution, **we should move the build files you've commited here to a /docs/ folder and set github pages to read out of only that folder.** This is preferable to having the build files pasted into the root directory like this (adding them into the root directory makes it much harder to tell what is a compiled file and what is a source file). 

**Ideally, we shouldn't have any compiled / build files in our repo at all as they're recreated in each new environment and will have slight arbitrary changes between machines.** The `package.json` file provides CI/CD servers and deploy services (netlify, now, Travis CI, etc) with all the info they need to build the website, and deploy it making the build files unnecesary!

**Comment by MykalMachon** [comment]
Additionally, I don't think we'll need Netlify for now if we're planning to use github pages for the site!

 **Both Netlify & Github pages are hosting platforms so we'd be hosting the website on two seperate servers**. the only downside with github pages being that we need a CI/CD server to handle the build & deploy step or a dedicated folder while Netlify automates that for us.

**Comment by MJJBennett** [comment]
@MykalMachon unfortunately, as far as I am aware, GitHub pages for user/org sites (which this is) doesn't actually allow reading out of an arbitrary folder, just the `master` branch (I would be extremely happy to be corrected on this)

I have gone ahead and uninstalled Netlify for now regardless.

**Comment by MykalMachon** [comment]
@MJJBennett well that's super unfortunate! I was assuming that we could because of [this article I found](https://help.github.com/en/articles/configuring-a-publishing-source-for-your-github-pages-site).

Is there really no option to use a /docs/ folder in the repo settings? 😞

**Comment by MJJBennett** [comment]
@MykalMachon Actually, it might be possible, and maybe it just doesn't show up without a buildable `/docs/` folder? I can try merging in this but in a `/docs` and see what happens... let's do that, actually.

**Comment by MykalMachon** [comment]
See #20

**Pull request closed without merging**
